### ISSUE TITLE
Support for Publishing Profile config transforms

### ISSUE THREAD

**Issue by dougrathbone** [sayedihashimi/package-web#61] opened 2013-07-02 04:08 UTC
As a user/developer it would be great to be able to have package-web apply different publishing profile transforms depending on the environment the package is being installed into. These should be applied in the same heirachy that the solution configuration transforms do (ie release first, profile second)

**Comment by sayedihashimi** [comment] 2013-07-02 04:58
This item is a duplicate of the previous issue #60. Let's continue the conversation over there, I have some thoughts on this.

**Closed as completed by sayedihashimi** 2013-07-02 04:58 UTC
